version: 0.2

env:
  variables:
    ECR_REPO_URI: "unset"

phases:
  install:
    commands:
      - go version
      - dockerd &
      - docker version
      - make lint-deps
  pre_build:
    commands:
      - make test
  build:
    commands:
      - docker build -t codebuild-go-test-app .
  post_build:
    commands:
      - $(aws ecr get-login --no-include-email --region eu-central-1)
      - docker tag codebuild-go-test-app:latest ${ECR_REPO_URI}:latest
      - docker push ${ECR_REPO_URI}:latest
